# 7-26task2
# -*- coding: utf-8 -*-
"""task1-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FZ4DA62IqR8f4eUogLOJyA-YToB_ndh
"""

# -*- coding: utf-8 -*-
"""code714-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2FX6TAxRjVKjgH29GHEWunOBGdgC3FX
"""

import csv
import sys
import datetime
import json
import ast
import os
from os import listdir
import os.path
from os import listdir
from os.path import isfile, join
import os
from distutils.dir_util import copy_tree
from shutil import copytree, copy2
import random
import json
import operator
import os
import http.client
import time
import gzip
from io import BytesIO
import json
from threading import Thread
import threading
from time import sleep
import http.client
import gzip
from io import BytesIO
import json
import random

conn = ''
headersDynamic = []
import _thread
import datetime
from multiprocessing import Process, Lock, Manager, Value
import collections
from difflib import SequenceMatcher
import _thread
import itertools
from itertools import islice
import multiprocessing
import gc
from io import StringIO
from multiprocessing import Pool
import glob
from os import listdir
from os.path import isfile, join

import shutil, os
import re


#services = ['Bird', 'Circ', 'Jump', 'Lime', 'LyftScooter', 'Movo', 'Scoot', 'Skip', 'Spin', 'Tier', 'Voi', 'Wind']
#citys = ['DC', 'Detroit', 'Lisbon', 'Madrid', 'MexicoCity', 'Paris', 'SanFrancisco', 'TelAviv', 'Zurich' ]
#services = ['Circ']
citys = ['Detroit']
# service = 'Tier2019-10-30'
dpath = 'E:/P1'

#full_path = os.path.realpath(__file__)
#dpath, realfilename = os.path.split(full_path)
#city='Detroit'
list1=[]
i=0
for city in citys:

    dataFilesPath = dpath + '/' + city
    onlyfiles = [f for f in listdir(dataFilesPath) if isfile(join(dataFilesPath, f))]

    service_city_date2num_of_scotter_in_use = {}
    service_city_date2all_scotter = {}
    for file in onlyfiles:
        try:
            date = re.findall("\d{4}-\d{2}-\d{2}", file)[0]
            service = re.findall("\D{4}", file)[0]
        except IndexError:
            date = re.findall("\d{4}-\d{2}", file)[0]
            service = re.findall("\D{4}", file)[0]
        txtFile = dataFilesPath + '/'+file
        date2num_of_scotter_in_use = {}


        if '.txt' in txtFile and 'lock' not in txtFile:
            f = open(txtFile, 'r',encoding='utf-8', errors='ignore')#encoding='utf-8', errors='ignore'

            dataDictionary = f.read()
            f.close()
            print('Reading File: ', txtFile)

            dataDictionary = json.loads(dataDictionary)
            scooterIDS = list(dataDictionary.keys())

            list1.append(len(scooterIDS))
            s = sum(list1)
            #print(list1)
            print(s)

            # for index in range(len(scooterIDS)):
            #     i=0;
            #     summ=0;
            #     for i in range(index):
            #         summ += len(scooterIDS)[i]




            # for id in scooterIDS:
            #     # lastLocations = -1
            #     # timeStamps = list(dataDictionary[id].keys())
            #     # timeStamps.sort()
            #
            #     for epoch in dataDictionary[id]:
            #         Latitude = dataDictionary[id][epoch][1]
            #         Longitude = dataDictionary[id][epoch][2]
            #         Timestamp = dataDictionary[id][epoch][0]
            #         Battery = dataDictionary[id][epoch][3]
            #
            # print(len(scooterIDS))




